OdeToFood/Controllers/ReviewsController.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OdeToFood.Controllers
{
    public class ReviewsController : Controller
    {
        OdeToFoodDb _db = new OdeToFoodDb();

        // GET: Reviews
        public ActionResult Index([Bind(Prefix = "id")] int RestaurantId)
        {
            var Restaurant = _db.Restaurants.Find(RestaurantId);
            if (Restaurant != null)
            {
                return View(Restaurant);
            }
            return HttpNotFound();
        }

        //GET: Reviews/create
        public ActionResult create(int restaurantID)
        {
            return View();
        }

        [HttpPost]
        public ActionResult create(RestaurantReview review )
        {
            if (ModelState.IsValid)
            {
                _db.RestaurantReviews.Add(review);
                _db.SaveChanges();
                return RedirectToAction("index", new { id = review.RestaurantID});
            }
            return View(review);
        }


        public ActionResult Edit(int id)
        {
            var review = _db.RestaurantReviews.Find(id);
            return View(review);
        }

        [HttpPost]
        public ActionResult Edit(RestaurantReview review)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(review).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("index", new { id = review.RestaurantID });
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

OdeToFood/Views/Reviews/Edit.cshtml
@model OdeToFood.Models.RestaurantReview

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RestaurantReview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(m=>m.RestaurantID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@section Scripts {
    
}*@

OdeToFood/Views/Reviews/Index.cshtml
@model OdeToFood.Models.Restaurant

@{
    ViewBag.Title = "Index";
}

<h2>Reviews of @Model.Name </h2>

<p>
    @Html.ActionLink("Create New", "Create", "Reviews", new { restaurantID = Model.ID }, null )
</p>

@Html.Partial("_ReviewPartialView", Model.Reviews )

OdeToFood/Views/Reviews/_ReviewPartialView.cshtml
@model IEnumerable<OdeToFood.Models.RestaurantReview>

<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Body )
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating )
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReviewerName )
            </th>
            <th></th>
        </tr>

    @foreach (var review in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => review.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => review.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => review.ReviewerName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id= review.ID })
            </td>
        </tr>
    }

    </table>

OdeToFood/Views/Reviews/create.cshtml
@model OdeToFood.Models.RestaurantReview

@{
    ViewBag.Title = "create";
}

<h2>create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create a new Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor( model => model.RestaurantID )  
        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>